# Generated by Django 2.0.7 on 2018-09-27 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('isInstructor', models.BooleanField(default=False)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(default='avatars/person-flat.png', upload_to='avatars/')),
                ('certificates_count', models.IntegerField(default=0)),
                ('designation', models.CharField(blank=True, choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Engineer', 'Engineer')], max_length=50, null=True)),
                ('office', models.CharField(blank=True, max_length=150, null=True)),
                ('institution', models.CharField(blank=True, max_length=150, null=True)),
                ('course_completed', models.ManyToManyField(related_name='course_completed', to='courses.Course')),
                ('course_joined', models.ManyToManyField(related_name='course_joined', to='courses.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
