# Generated by Django 2.0.7 on 2018-10-04 12:54

import apps.profiles.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=apps.profiles.utils.default_avatar_image_path, upload_to=apps.profiles.utils.default_avatar_image_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course_completed',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_completed', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course_joined',
            field=models.ManyToManyField(blank=True, null=True, related_name='course_joined', to='courses.Course'),
        ),
    ]
