# Generated by Django 2.0.7 on 2018-10-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20181004_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course_completed',
            field=models.ManyToManyField(blank=True, related_name='course_completed', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course_joined',
            field=models.ManyToManyField(blank=True, related_name='course_joined', to='courses.Course'),
        ),
    ]
